### ISSUE TITLE
Case insensitive options

### ISSUE THREAD

**Issue by daanhaitsma** [modulero/cruddy-tests#3]
Currently, when running the following command:
```
php artisan make:cruddy-tests Foo --except=View
```
These tests will be created:
- ViewAnyFooTest
- **ViewFooTest**
- CreateFooTest
- UpdateFooTest
- DeleteFooTest

Although the README states the names need to match the ones in the config, I personally feel that capitalisation should be ignored here.

**Comment by richje22** [comment]
Fixed in v1.2.0.
